name: PR comments ops

on: 
  pull_request_review_comment:
    types: [created]
jobs:
  build:
    name: PR comment handler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/handle-pr-comment
