name: Greet Everybody (sub-project)
# This workflow is triggered on pushes to the sub-project
on:
  push:
    paths:
    - 'sub-project/**'

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.9.3'
    - run: go run sub-project/hello.go
